name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]  # 触发分支（如 main/master）

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 的 Ubuntu 环境
    steps:
      # 步骤 1：拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2：设置 Node.js 环境（如果项目依赖 Node.js）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 与项目使用的 Node 版本一致

      # 步骤 3：安装依赖（如 npm install / pnpm install）
      - name: Install dependencies
        run: npm install

      # 步骤 4：构建项目（如 npm run build）
      - name: Build project
        run: npm run build

      # 步骤 5：部署到 Cloudflare Workers
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}  # 引用 GitHub Secrets 中的令牌
          command: deploy  # 执行部署命令